"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

const faqs = [
  {
    question: "How does the AI model work?",
    answer:
      "Our neural networks analyze 200+ behavioral signals per employee through brief weekly pulse checks and optional wearable integration. The system builds individualized performance models that identify peak productivity windows, energy patterns, and collaboration dynamics.",
  },
  {
    question: "What insights do managers receive?",
    answer:
      "Personalized playbooks for each team member generated by predictive algorithms: optimal scheduling recommendations, workload distribution analysis, and proactive intervention prompts. Data-driven guidance, not intuition.",
  },
  {
    question: "How is data privacy handled?",
    answer:
      "Employees own their data. Differential privacy techniques ensure managers see aggregated insights and recommendations, never raw individual data. Full data portability and one-click deletion at any time.",
  },
  {
    question: "What ROI can we expect?",
    answer:
      "Organizations see 15-25% productivity gains on average. The platform reduces burnout-related attrition by flagging risk signals 3 weeks early. Better output, lower healthcare costs, higher retention.",
  },
  {
    question: "How is this different from engagement surveys?",
    answer:
      "Surveys capture a snapshot. NexFlow builds continuous behavioral models that detect pattern shifts in real-time, predicting optimal conditions and surfacing anomalies before they become problems.",
  },
  {
    question: "What's the employee adoption rate?",
    answer:
      "94% voluntary participation. Employees receive their own personalized insights about energy patterns and productivity rhythms. They benefit directly from the data they contribute.",
  },
  {
    question: "How quickly does the model calibrate?",
    answer:
      "Initial behavioral profiles in 2 weeks. The model reaches statistical significance for team-level predictions within 30 days. Measurable productivity improvements guaranteed within 90 days.",
  },
];

function FAQItem({
  question,
  answer,
  isOpen,
  onToggle,
}: {
  question: string;
  answer: string;
  isOpen: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="border-b border-[#e5e0d8]">
      <button
        onClick={onToggle}
        className="flex w-full items-center justify-between py-5 text-left gap-4"
      >
        <span
          className="text-left text-[#000]"
          style={{
            fontFamily: 'var(--font-inter), Inter, sans-serif',
            fontWeight: 500,
          }}
        >
          {question}
        </span>
        <ChevronDown
          className={cn(
            "h-5 w-5 text-[#94877c] transition-transform duration-200 shrink-0",
            isOpen && "rotate-180"
          )}
        />
      </button>
      <div
        className={cn(
          "overflow-hidden transition-all duration-200",
          isOpen ? "max-h-96 pb-4" : "max-h-0"
        )}
      >
        <p
          className="text-[#94877c]"
          style={{ fontFamily: 'var(--font-inter), Inter, sans-serif' }}
        >
          {answer}
        </p>
      </div>
    </div>
  );
}

export function EnterpriseFAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section className="py-16 md:py-24 bg-[#fcf6ef]">
      <div className="container mx-auto max-w-3xl px-6 md:px-16">
        <div className="text-center mb-12">
          <p
            className="text-sm text-[#1F4D3A] uppercase tracking-wider mb-4"
            style={{
              fontFamily: 'var(--font-inter), Inter, sans-serif',
              fontWeight: 500,
            }}
          >
            FAQ
          </p>
          <h2
            className="text-3xl md:text-[42px] text-[#000]"
            style={{
              fontFamily: 'var(--font-halant), Halant, Georgia, serif',
              fontWeight: 400,
              letterSpacing: '-0.05em',
              lineHeight: '110%',
            }}
          >
            Common questions
          </h2>
        </div>
        <div className="divide-y divide-[#e5e0d8] border-t border-[#e5e0d8]">
          {faqs.map((faq, index) => (
            <FAQItem
              key={index}
              question={faq.question}
              answer={faq.answer}
              isOpen={openIndex === index}
              onToggle={() => setOpenIndex(openIndex === index ? null : index)}
            />
          ))}
        </div>
      </div>
    </section>
  );
}
